baseURL = 'https://hdonliu.github.io/'
languageCode = 'en-us'

# 是否包括中日韩文字
hasCJKLanguage = true

title = 'hdonBlog'

# 模版
theme = "DoIt"


#[author]
#  name = 'hdLiu'
  
[params.home.profile]
  # 主页显示头像的 URL
  avatarURL = "/images/avatar.jpg"

[menu]
  [[menu.main]]
    identifier = "posts"
    pre = ""
    post = ""
    name = "Posts"
    url = "/posts/"
    # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "life"
    pre = ""
    post = ""
    name = "Life"
    url = "/life/"
    # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 4
  [[menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/about"
    title = ""
    weight = 5
  [[menu.main]]
    identifier = "github"
    pre = "<i class='fab fa-github fa-fw' aria-hidden='true'></i>"
    post = ""
    name = ""
    url = "https://github.com/hdonLiu"
    title = ""
    weight = 6
   [[menu.main]]
    identifier = "email"
    pre = "<i class='far fa-envelope fa-fw' aria-hidden='true'></i>"
    post = ""
    name = ""
    url = "mailto:l916670409@gmail.com"
    title = ""
    weight = 7


# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

# 搜索设置
[outputs]
  home = ["HTML", "RSS", "JSON"]
[params.search]
  enable = true
  # 搜索引擎的类型 ("algolia", "fuse")
  type = "fuse"
  # 文章内容最长索引长度
  contentLength = 400
  # 最大结果数目
  maxResultLength = 10
  # 结果内容片段长度
  snippetLength = 30
  # 搜索结果中高亮部分的 HTML 标签
  highlightTag = "em"
  [params.search.fuse]
    isCaseSensitive = false
    minMatchCharLength = 2
    findAllMatches = false
    location = 0
    threshold = 0.3
    distance = 100
    ignoreLocation = false
    useExtendedSearch = false
    ignoreFieldNorm = false
